# Generated by Django 4.2.9 on 2024-03-10 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Желание', 'verbose_name_plural': 'Желания'},
        ),
        migrations.AddField(
            model_name='wish',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
