# Generated by Django 4.2.9 on 2024-03-16 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0002_alter_wish_options_wish_author_alter_wish_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='slug',
        ),
        migrations.AlterField(
            model_name='wish',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
